public class GameConstants 
{
    public const float START_MONEY = 200, GIFT_1_COUNT = 10, GIFT_2_COUNT = 25, GIFT_3_COUNT = 50,
        LOSS_1_COUNT = 5, LOSS_2_COUNT = 15, LOSS_3_COUNT = 50,
        HOUSING_1_MONEY_SURPLUS = 1f, HOUSING_2_MONEY_SURPLUS = 1f, INDUSTRIAL_1_MONEY_SURPLUS = 10F,
        INDUSTRIAL_2_MONEY_SURPLUS = 22F,
        TREE_LIFEPOWER_SURPLUS = 1f, LIFEPOWER_SURPLUS_HOUSING = 0.01f,
        MAX_HOUSING_1_VOLUME = 20f, MAX_HOUSING_2_VOLUME = 50f,
        PEOPLE_SURPLUS = 1f,
        LIFEPOWER_LIMIT_1 = 36f, LIFEPOWER_LIMIT_2 = 72f, LIFEPOWER_LIMIT_3 = 120f, LIFEPOWER_LIMIT_4 = 250f,
        XCARD_ROLL_COST = 100f;
    public const byte FIRE_EVENT_LENGTH = 4, ILLNESS_EVENT_LENGTH = 7;
    public static readonly string HEX_COLLIDER_TAG = "Landscape";
}
